# Scavenger Deathmath Localization: English
scav.dm=Scavenger Deathmatch
#==============================================================================
#	HUD
#==============================================================================
scav.score=Score: %1%
scav.score.lead=LEAD
scav.score.tied=TIED
scav.points.format=%1%/%2%
scav.points.next=Points to next:
scav.score.time=Time: 
scav.score.points=Points
scav.score.deaths=Deaths
scav.score.ping=Ping
scav.score.noone=No players have joined the game!
scav.score.header=%1%: %2%/%3%
scav.score.header.time=%1% | Map Time Remaining: %2%
scav.score.time.format=%02i:%02i
scav.score.mode=     MODE: %1%
scav.score.spectators=Spectators: %1%
scav.score.unassigned=Players
scav.score.team.point=%1% - %2% Point
scav.score.team.points=%1% - %2% Points
scav.score.team.win=%1% - %2% Win
scav.score.team.wins=%1% - %2% Wins
#separator for spectator list
scav.score.spectators.sep=, 
scav.round.winner.team=Round Winner
scav.round.winner.player=Round Winner
scav.round.winner.announce=%1% wins the round!
scav.team.select=Select Team
scav.team.select.cooldown=You must wait %1% seconds before changing teams.
scav.team.select.spectate=%1% is now spectating.
scav.team.select.dm=%1% has joined the fray!
scav.team.select.join=%1% has joined %2%.
scav.team.select.switch=%1% has left %3% and joined %2%.
scav.team.select.nojoin=%1% is not joinable!
scav.team.select.nolives=You do not have any remaining lives!
scav.team.select.nolives.team=%1% does not have any remaining lives!
scav.team.spectate=Spectators
scav.team.red=Red Team
scav.team.blue=Blue Team
scav.team.green=Green Team
scav.team.yellow=Yellow Team
scav.team.orange=Orange Team
scav.team.purple=Purple Team
scav.team.brown=Brown Team
scav.team.teal=Teal Team
scav.menu=MAIN MENU
scav.menu.main=Main
scav.menu.eq=Equipment
scav.menu.eq.secondary=Secondary Weapon
scav.menu.eq.desc.default=This is a gun
scav.menu.eq.desc.alc=Originally designed as a tool to end world hunger, the technology behind the Alchemy Gun had so much potential in military applications that the original project was scrapped entirely and the team behind it found a new job in making it into a tool of war. This device will disassociate the elements of any object and store them for later use. A variety of useful items can be made using these gathered resources, such as health kits, ammunition, and powerful weapons. \n \n Recommended for expert combatants.
scav.menu.eq.desc.bhg=An awe and terror inspiring machine of war, the CF-2200 "Black Hole Gun" is one of the most dreaded weapons to see on the other side of the battlefield. It is capable of using any nearby matter to fuel its internal gravity manipulator. The weapon uses this manipulator to turn loose junk into a storm of deadly projectiles that fly toward the point of impact. Many users have reported a strange slowing of time during an active "black hole". \n \n This weapon is recommended for advanced combatants.
scav.menu.eq.desc.bup=A standard pistol. While it may lack the immediate appeal of some of the other weapons available on the battlefield, its versatility makes it a life saver. This weapon feeds on your battle suit's energy reserves, which means that with proper use, you will never run out of ammo. The weapon can also be primed to fire up to ten beams at once with its secondary fire. Additional damage is inflicted upon enemy combatants that are already injured. \n \n Recommended for newer combatants.
scav.menu.eq.desc.cd=Much like its deadlier cousin, the SC-08 "Scavenger Cannon", the Capture Device is capable of picking up and storing various objects. Unlike the Scavenger Cannon, it has a capacity of one object and will not modify the original object in any way. The convenience of this is that while objects become irrecoverable or unstable once they enter the Scavenger Cannon, anything trapped in the Capture Device can be released at any time or injected into the Scavenger Cannon. \n \n Recommended for experienced combatants.
scav.menu.eq.gadget=Gadget - Not yet available.
scav.menu.player=Player Model
scav.menu.player.skin=Skin
scav.menu.player.bodygroup=Bodygroups:
scav.menu.options=Options
scav.menu.spectate=Spectate
scav.menu.join=Join Game
scav.menu.instruction=Hold down %1% to open the menu and join the game.
scav.mode.dm=Deathmatch
scav.mode.tdm=Team Deathmatch
scav.mode.ctf=Capture the Flag
scav.mode.cell=Cell Control
scav.mode.hoard=Hoard
scav.mode.survive=Survival
scav.mode.cap=Capture
scav.mode.custom=Mission
scav.map.timeup=Map time limit reached. Voting for next map has begun.
scav.nokey=<UNBOUND>
scav.sdm.headshot=Headshot!
#==============================================================================
#	Stats
#==============================================================================
scav.stats.time=Play Time
scav.stats.games=Games Played
scav.stats.games.won=Wins
scav.stats.games.lost=Losses
scav.stats.games.tied=Draws
scav.stats.points=Points
scav.stats.points.onelife=Longest Point Streak
scav.stats.kills=Frags
scav.stats.kills.onelife=Longest Killing Spree
scav.stats.kills.gibs=Gibs
scav.stats.headshots=Headshots
scav.stats.deaths=Deaths
scav.stats.deaths.self=Suicides
scav.stats.dmg=Damage
scav.stats.heal=Healing
#==============================================================================
#	Vote Menu
#==============================================================================
scav.vote.title=M  A  P     V  O  T  E
scav.vote.settings.voted=Settings with votes:
scav.vote.settings.all=All available settings files:
scav.vote.map=Map
scav.vote.settings=Setting Name
scav.vote.votes=Votes
scav.vote.deadline=%1% seconds remaining to vote for the next map!
scav.vote.button=VOTE!
scav.vote.voted=%4%%1%%#FFF% has voted for the map %#0F0%%2%%#FFF% with settings file %#0F0%%3%%#FFF%.
scav.vote.ending=%#FFF%SDM Map voting will end in %#0F0%%1%%#FFF% seconds!
scav.vote.ended=%#FFF%Voting has ended. %#0F0%%1%%#FFF% on %#0F0%%2%%#FFF% has won the map vote. Changing maps in %#0F0%%3%%#FFF%..
scav.vote.ended.notime=%#FFF%Voting has ended. %#0F0%%1%%#FFF% on %#0F0%%2%%#FFF% has won the map vote. Changing maps now!
scav.vote.ended.count=%#0F0%%1%%#FFF%..
scav.vote.notallowed=%#FFF%Cannot vote on this server. %#0F0%sdm_allowvote%#FFF% must be set to 1
scav.vote.called=A majority vote of at least %1%%PERCENT% wishes to change the map at this time.
scav.vote.called.minority=A vote of at least %1%%PERCENT% wishes to change the map at this time.
scav.config.title=%1%: %2%
scav.config.unknown=?
scav.config.false=Off
scav.config.true=On
scav.config.0=None
scav.config.author=Author: %1%
scav.config.author.anon=Anonymous
scav.config.mode=Mode: %1%
scav.config.teams=%1%-Team
scav.config.friendlyfire=Friendly Fire %1%
scav.config.limit.points=Point Limit: %1%
scav.config.limit.time=Time Limit: %1%
scav.config.scale.damage=Damage Scale: $1$x
scav.config.mods=Modifiers: %1%
#separator for mod list
scav.config.mods.sep=, 
#==============================================================================
#	Config File mods
#==============================================================================
scav.config.mod.rocketjump=Rocket Jumping
scav.config.mod.rocketjump.desc=Waltzing where eagles dare.
scav.config.mod.selfdamage=Self-Damage
scav.config.mod.selfdamage.desc=Stop hitting yourself!
scav.config.mod.instagib=Insta-Gib
scav.config.mod.instagib.desc=One shot, one bloody kill.
scav.config.mod.cloak=Cloaking Device
scav.config.mod.cloak.desc=Now you see me, now you don't.
scav.config.mod.falldmg=Fall Damage
scav.config.mod.falldmg.desc=Look out below!
scav.config.mod.drown=Drowning
scav.config.mod.drown.desc=Don't hold your breath, 'cause it'll only make you blue.
scav.config.mod.vamp=Vampire Mode
scav.config.mod.vamp.desc=Only blood will satiate your hunger.
#
# not *totally* sure what these mods are supposed to be at present
#
scav.config.mod.champion=Champion
scav.config.mod.toxic=Toxic
scav.config.mod.blastdeath=Blast Death
#==============================================================================
#	Achievements
#==============================================================================
scav.achievement=%1% has achieved %2%!
scav.achievement.triplegib=Two Is Company, Three Is Chunks
scav.achievement.triplegib.desc=Kill three players with one explosion.