# Scavenger Deathmath Localization: English
#==============================================================================
#	HUD
#==============================================================================
scav.score=Score: 
scav.score.lead=LEAD
scav.score.tied=TIED
scav.points.format=%1%/%2%
scav.points.next=Points to next:
scav.score.time=Time: 