# Scavenger Deathmath Localization: Yarr
scav.dm=Scavenger Deathmatch
#==============================================================================
#	HUD
#==============================================================================
scav.score=Treasure: %1%
scav.score.lead=AHEAD
scav.score.tied=EVEN
scav.points.format=%1% o' %2%
scav.points.next=Treasure ta next:
scav.score.time=Time: 
scav.score.noone=No crewmates have manned the ship!
scav.score.header=%1% - %2% o' %3% crewmates
scav.score.header.time=%1% | Chart Time Remaining: %2%
scav.score.time.format=%02i:%02i
scav.score.mode=     VOYAGE: %1%
scav.score.spectators=Watchmen: %1%
scav.score.unassigned=Crew
scav.score.team.point=%1% - %2% Treasure
scav.score.team.points=%1% - %2% Treasures
scav.score.team.win=%1% - %2% Victory
scav.score.team.wins=%1% - %2% Victories
#separator for spectator list
scav.score.spectators.sep=, 
scav.round.winner.team=Crew Victorious
scav.round.winner.player=Crewman Victorious
scav.round.winner.announce=%1% t'was victorious!
scav.team.select=Select Crew
scav.team.select.cooldown=Ye must be waitin' %1% more seconds a'fore changin' yer crew.
scav.team.select.spectate=%1% is now watchin' things.
scav.team.select.dm=%1% has joined the scuffle!
scav.team.select.join=%1% 'as joined %2%.
scav.team.select.switch=%1% 'as left %3% an' joined %2%.
scav.team.select.nojoin=%1% ain't acceptin' no crew!
scav.team.select.nolives=Yer lot o' lives ran out!
scav.team.select.nolives.team=%1%'s crew ran their lot!
scav.team.spectate=Watchmen
scav.team.red=Red Crew
scav.team.blue=Blue Crew
scav.team.green=Green Crew
scav.team.yellow=Yellow Crew
scav.team.orange=Orange Crew
scav.team.purple=Purple Crew
scav.team.brown=Brown Crew
scav.team.teal=Seafoam Crew
scav.menu=MAIN MENU
scav.menu.main=Main
scav.menu.eq=Arms
scav.menu.eq.secondary=Second'ry Arm
scav.menu.eq.desc.default=This be a firearm
scav.menu.eq.desc.alc=Black magic, this be. This 'ere device will store plenty o' booty, 'an remember it too. All sorts of useful supplies can be made using its gathered booty, such as healin', munitions, an' powerful firearms. \n \n It be recommended fer expert crewmates.
scav.menu.eq.desc.bhg=A right terror, this be, capable o' sinkin' even the largest o' ships. It be turnin' things inta fuel fer its whirlpools. Can even be directin' what paths they take.\n \n This 'ere firearm is recommended fer advanced crewmates.
scav.menu.eq.desc.bup=A regular firearm. It may not be fancy, but by Jove will it get the job done just the same. If yer not constantly runnin' about the place, ye'll never be runnin' outta shots with this 'ere weapon. Ye can charge up a whole barrage o' pain with this while yer waitin' in a lull. \n \n It be recommended fer newer crewmates.
scav.menu.eq.desc.cd=Much like its deadlier cousin, the SC-08 "Scavenger Cannon", the Capture Device is capable of picking up and storing various objects. Unlike the Scavenger Cannon, it has a capacity of one object and will not modify the original object in any way. The convenience of this is that while objects become irrecoverable or unstable once they enter the Scavenger Cannon, anything trapped in the Capture Device can be released at any time or injected into the Scavenger Cannon. \n \n Recommended for experienced combatants.
scav.menu.eq.gadget=Gadget - We got nothin'.
scav.menu.player=Uniform
scav.menu.player.skin=Fabric
scav.menu.player.bodygroup=Styles:
scav.menu.options=Options
scav.menu.spectate=Jus' Watch
scav.menu.join=Climb Aboard
scav.menu.instruction=Hol' down %1% ta open yer menu an' climb aboard!
scav.mode.dm=Deathmatch
scav.mode.tdm=Crew Deathmatch
scav.mode.ctf=Capture the Booty
scav.mode.cell=Cell Control
scav.mode.hoard=Hoard
scav.mode.survive=Survival
scav.mode.cap=Capture
scav.mode.custom=Mission
scav.map.timeup=Our time on this 'ere chart's drawin' to an end. Votin' fer the next one has begun.
scav.nokey={UNBOUND}
scav.sdm.headshot=Headshot!
#==============================================================================
#	Stats
#==============================================================================
scav.stats.time=Time Aboard
scav.stats.games=Voyages Sailed
scav.stats.games.won=Victories
scav.stats.games.lost=Defeats
scav.stats.games.tied=Ties
scav.stats.points=Booty
scav.stats.points.onelife=Biggest Chest
scav.stats.kills=Lives Taken
scav.stats.kills.onelife=Most Lives Taken
scav.stats.kills.gibs=Smithereens
scav.stats.headshots=Headshots
scav.stats.deaths=Deaths
scav.stats.deaths.self=Planks Walked
scav.stats.dmg=Damage
scav.stats.heal=Healin'
#==============================================================================
#	Vote Menu
#==============================================================================
scav.vote.settings.voted=Settin's with votes:
scav.vote.settings.all=All yer available settin's:
scav.vote.map=Chart
scav.vote.settings=Settin' Name
scav.vote.votes=Votes
scav.vote.deadline=Chart Vote comin' to a close! Only %1% seconds remaining ta voice yer choice!
scav.vote.button=CHOOSE!
scav.vote.voted=%4%%1%%#FFF% 'as voted fer the chart %#0F0%%2%%#FFF% wif th' settin's o' %#0F0%%3%%#FFF%.
scav.config.title=%2%, in %1%
scav.config.unknown=?
scav.config.false=No
scav.config.true=Aye,
scav.config.0=unlimited!
scav.config.author=Yer Bosun be %1%
scav.config.author.anon=Anonymous
scav.config.mode=Yer Voyage be %1%
scav.config.teams=%1% Crews
scav.config.friendlyfire=%1% Friendly Fire
scav.config.limit.points=Total Booty be %1%
scav.config.limit.time=Total Time be %1%
scav.config.scale.damage=Damage Scale: $1$x
scav.config.mods=Complications: %1%
#separator for mod list
scav.config.mods.sep=, 
#==============================================================================
#	Config File mods
#==============================================================================
scav.config.mod.rocketjump=Roman Candle Jumping
scav.config.mod.rocketjump.desc=Ye'll be sailin' the seven skies!
scav.config.mod.selfdamage=Self-Harm
scav.config.mod.selfdamage.desc=Mind yer powder.
scav.config.mod.instagib=Insta-Gib
scav.config.mod.instagib.desc=Every last shot be a cannon.
scav.config.mod.cloak=Fog Be Rollin' In...
scav.config.mod.cloak.desc=...an' the lighthouse be dark.
scav.config.mod.falldmg=Fallin' Hurts
scav.config.mod.falldmg.desc=Don't walk the plank!
scav.config.mod.drown=Drownin'
scav.config.mod.drown.desc=Always be a threat.
scav.config.mod.vamp=Bloodsuckers
scav.config.mod.vamp.desc=Their deaths be fuelin' yer life.
#
# not *totally* sure what these mods are supposed to be at present
#
scav.config.mod.champion=Champion
scav.config.mod.toxic=Toxic
scav.config.mod.blastdeath=Blast Death
#==============================================================================
#	Achievements
#==============================================================================
scav.achievement=%1% has achieved %2%!
scav.achievement.triplegib=Two be Company, Three be Chum
scav.achievement.triplegib.desc=Kill three crewmen with one explosion.